language: python
python: 3.8.1
before_script:
  - pip install nose
script:
  - docker-compose build
  - docker-compose run --entrypoint "bash -c 'pip install nose && cd /app && nosetests'" launch-graph
